version: '3.9'
services:
    node:
        restart: on-failure
        build: ./node
        ports:
            - '4000:4000'
    nginx:
        build: ./nginx
        ports:
            - '80:80'
        depends_on:
            - node